from Image import Image
import PIL
from pyPdf import PdfFileWriter, PdfFileReader
import StringIO
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

packet = StringIO.StringIO()
# create a new PDF with Reportlab

image_data = 'iVBORw0KGgoAAAANSUhEUgAAAMYAAAA3CAYAAABXVTXhAAAHEUlEQVR4Xu1dOSx9TxQe28/SailRoiChElRCJaFAqAiFJUREiFgi9hCxViQUJCoKBQoFCQVKFApaSvvyzzfJyPyv+7a7vXvnnkleyL0z8+Z8Z745c84sL+bn5+eHeTw1NTVxCVZWVvjfx8dHdn19zW5ubtjZ2Rn7+vriz1NTU1lFRQUrKCjwuMTUfLsRiFGRGFrQTk5O2O7uLnt6eiKC2N2jFKnfF8QQuiKCKNJrHRDDV8QIRJC4uDhWWVnJp1gpKSkOwO7Pr2hra2MvLy8sISGB1dbWunpK60tiyATZ2Nj49UHwHOQoKSlh6enp/uy9Nkrd2Nj4W3tMTAyLj49nPT09rsRaGWIghrC6umpIrZeXlwzTrKurq9/yaWlprLS01NWjmiFho1hIEKOhoYHJAxICIuXl5VFs2d+vVoIYzc3N7Pv7m42OjvLIk9GEaNbBwQE7PT3lJh8pOTmZFRYWcitipm6jbVKpnCCGGMAQENnb2+MiYjpbV1fnmoFICWJMTU2x29tbBoLk5ORY0pdgQQ4PD9nDw8NvfagbUy2rvsOShupUgrZvbm6yj48PhimLnGBZtc/wPtDzcMqGk0fUr7Xs9/f3bHx8nLcVyS0hdSWIIUYemGOYZSsTFAeCwIqIhNGtrKyMk8RNVkQ4t2inXucPRgCniJGUlMTm5ub+qMhtEUMliAEfYWlpiWVkZLCuri4refFb1/PzMyfHzs7O/5x1t1gRmRSI+tTU1PApoNeSliBw0IeGhhwfgJQgBnyD3t5ePkouLy/b3hf0nHVYDnREp62IIARkx6gPn0hvRLYdFIu/AAQRDjpk6uzsdDR6pQQxoBOrHPBI9AtCQoH4iFV1lHfKisCKtbe38yaDGIGmKZHI5Ka8kG9tbe03WlhfX++YFfxDjOHhYR6R8dqeosXFRQ6gk+DJnUjPimAEx4KhvCaC/8UiIkZC+R1CxKEWGOHzYA8YPpAX0ThVrEQgUm5tbbGjoyP+GtHBqqoq2/mrSwwRiZEdMj3nTO+9vCfRyRVOOMjb29t8KoM4ebSSsCL7+/vs8/PTUDOCOcLad8B4YmIiJKEMNcRFhWCV19fXeYtgkTEAhhpEzDRfdyolwn2yYo0QQ5h4J0JwGElHRkZ4PBzWwy0J0wG0TSQMOniGpPdOrJ8Eaj+c0by8PJaZmcmysrIcd0qjiStwnJ6e5jMau51yW30MbYQBnTY/P58zHoq1mvEtLS08YtTX1+eooxbNzuK374ZFHhgYYO/v77z/2OWU20oMoTQ5wiArEuQQJLFib5KYixYXF7Pq6mq/9RnfyOuEU+4IMYTGhON4cXHBV6rlhKhKdnY2tyT4GCEK6kfwAPPuhYUF33QUvwpqp1PuKDFkBYL1iKwgmiOfshN5EGnBHDpSomhP8/m10/hFbruc8qgRQ6s4+TgqjqXK6wLIG0mkxsxOW790KJXk1Drlk5OTpv1X1xAjGFHOz8+Dhj61pFFtoUulTmyXLBhYBwcH2evrK8vNzeULvmaSa4lhRigq608EQA6xQG02AEPE8GcfMiU1tonf3d3x6a08zQ204Cv2cYkdv6Kc3nP5mbxVXTzH9+H/f//+8e3q2pC/WM9CPjO7IIgYprqIPwsjwBGMBHpk0eYXHTwcMskEkcuBFLOzs3+UIDvkRte0iBj+7NumpG5tbeXlx8bGTDu5RhqCiGZHRwcnJ4iht1AsQrmIbvb390e8Q4CIYUQzVCbqCICcb29vfEo1Pz+v2x6xsTQxMTFiEhMxoq5iaoARBGA1cCgNW4AC+RLI093dzY/NRuqMEzGMaIXKuAIB4UsE2zgqO+OR3AlAxHCFiqkRRhEQG0eDRaDEkQT4G7hJJpzNq0QMoxqhcq5AIByrgYaKm2SwxQg7ckMlIkYohOi96xEQViPYLTHwN3AvAM5y4AQgTgIGS0QM16udGhgKAeytm5mZ4dmCrVuI22RC5cN7IkYo1Om9JxAQ6xah7sOV8wXbbEjE8ITaqZGhEJBDs3CyMV3Su1dLzofLJ+Bv6DnjRIxQiNN7zyCATo8LMcStkbgYAwTRdnzkw9lxnL8PRA4ihmfUTg0NFwFEqkAQONqBLosORQ4iRrhoUz5PIRDOZdEyOWJjY/k1ryIRMTylbmpspAjo3YUr/1iNvCFR/n0VIkakSFN+TyKgvalG/rEa3P+LJN/5S8TwpJqp0UYR0P5YTVFREb+9UnsrDRHDKMJUzrMIaP0P+USh+AkFIoZn1UsNN4sACIIp1vHx8Z9fnyJimEWXyiuFgHDWiRhKqZWEsQoBIoZVSFI9SiFAxFBKnSSMVQgQMaxCkupRCgEihlLqJGGsQoCIYRWSVI9SCBAxlFInCWMVAkQMq5CkepRCgIihlDpJGKsQIGJYhSTVoxQCRAyl1EnCWIUAEcMqJKkepRD4Dw16xI3pOz+VAAAAAElFTkSuQmCC'
img_height = 1.5 * inch  # max image height
img_file = StringIO.StringIO(image_data.decode('base64'))
img_file.seek(0)
img = PIL.Image.open(img_file)
can = canvas.Canvas(packet, pagesize=letter)

can.drawImage(ImageReader(img), 100, 100)
can.save()


# move to the beginning of the StringIO buffer
packet.seek(0)
new_pdf = PdfFileReader(packet)
# read your existing PDF
existing_pdf = PdfFileReader(file("blank.pdf", "rb"))
output = PdfFileWriter()
# add the "watermark" (which is the new pdf) on the existing page
page = existing_pdf.getPage(0)
page.mergePage(new_pdf.getPage(0))

output.addPage(page)
# finally, write "output" to a real file
outputStream = file("destination2.pdf", "wb")
output.write(outputStream)
outputStream.close()
